substitutions:
  _REGION: asia-south1
  _REPO: docs-highlight-rag

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - ingest/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/ingest:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - api/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/api:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/ingest:latest"]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/api:latest"]

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/ingest:latest
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/api:latest
